services:
  - type: web
    name: twilio-transcription-service
    env: python
    plan: starter
    buildCommand: |
      pip install torch
      pip install git+https://github.com/openai/whisper.git
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 